// templates/application/Vite/vue3/js/src/App.vue
<template>
  <div class="{{CONTAINER}}">
    <div>Name: {{ NAME }}</div>
    <div>Type: {{ TYPEWEB }}</div>
    <div>Tools build: {{ TOOLSBUILD }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({});
</script>

// templates/application/Webpack5/SPA/react/ts/src/App.tsx
import React from "react";
import { hot } from 'react-hot-loader/root';

import "./styles/index.{{CSS_EXTENSION}}";

const App = () => (
  <div className="{{CONTAINER}}">
    <div>Name: {{ NAME }}</div>
    <div>Tools build: {{ TOOLSBUILD }}</div>
    <div>Type: {{ TYPEWEB }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
);

export default hot(App);
