// templates/application/SPA/vue3/ts/src/App.vue
<template>
  <div class="{{CONTAINER}}">
    <div>Name: {{ NAME }}</div>
    <div>Type: {{ TYPEWEB }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({});
</script>

// templates/application/SPA/react/ts/src/App.tsx
import React from "react";
import ReactDOM from "react-dom";

import "./styles/index.{{CSS_EXTENSION}}";

const App = () => (
  <div className="{{CONTAINER}}">
    <div>Name: {{ NAME }}</div>
    <div>Type: {{ TYPEWEB }}</div>
    <div>Framework: {{ FRAMEWORK }}</div>
    <div>Language: {{ LANGUAGE }}</div>
    <div>CSS: {{ CSS }}</div>
  </div>
);

ReactDOM.render(<App />, document.getElementById("app"));
